### ISSUE TITLE
Unable to instantiate a seeder, make sure to enable a seeder feature like seeder_unix for example on unix platforms.

### ISSUE THREAD

**Issue by qxzhou1010** [zama-ai/tfhe-rs#998]
I am trying to compile and run some examples in the source code of `tfhe-rs`. I use the Ubuntu 22.04.3 LTS. 

However, I occur the below problem. Please help me. 

```
    Finished dev [unoptimized + debuginfo] target(s) in 1m 28s
     Running `target/debug/examples/pbs_count`
thread 'main' panicked at tfhe/src/core_crypto/seeders.rs:122:12:
Unable to instantiate a seeder, make sure to enable a seeder feature like seeder_unix for example on unix platforms.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:196:5
   3: core::panicking::panic_str
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:171:5
   4: core::option::expect_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1980:5
   5: core::option::Option<T>::expect
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:894:21
   6: tfhe::core_crypto::seeders::new_seeder
             at ./tfhe/src/core_crypto/seeders.rs:122:5
   7: tfhe::shortint::engine::ShortintEngine::new
             at ./tfhe/src/shortint/engine/mod.rs:313:31
   8: tfhe::shortint::engine::LOCAL_ENGINE::__init
             at ./tfhe/src/shortint/engine/mod.rs:25:65
   9: tfhe::shortint::engine::LOCAL_ENGINE::__getit::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/common/thread_local/fast_local.rs:99:25
  10: std::sys::common::thread_local::lazy::LazyKeyInner<T>::initialize
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/common/thread_local/mod.rs:54:25
  11: std::sys::common::thread_local::fast_local::Key<T>::try_initialize
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/common/thread_local/fast_local.rs:190:27
  12: std::sys::common::thread_local::fast_local::Key<T>::get
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/common/thread_local/fast_local.rs:173:25
  13: tfhe::shortint::engine::LOCAL_ENGINE::__getit
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/common/thread_local/fast_local.rs:91:21
  14: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:269:32
  15: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  16: tfhe::shortint::engine::ShortintEngine::with_thread_local_mut
             at ./tfhe/src/shortint/engine/mod.rs:299:9
  17: tfhe::shortint::client_key::ClientKey::new
             at ./tfhe/src/shortint/client_key/mod.rs:47:9
  18: tfhe::integer::client_key::ClientKey::new
             at ./tfhe/src/integer/client_key/mod.rs:136:18
  19: <tfhe::high_level_api::keys::inner::IntegerClientKey as core::convert::From<tfhe::high_level_api::keys::inner::IntegerConfig>>::from
             at ./tfhe/src/high_level_api/keys/inner.rs:126:19
  20: tfhe::high_level_api::keys::client::ClientKey::generate
             at ./tfhe/src/high_level_api/keys/client.rs:29:18
  21: tfhe::high_level_api::keys::generate_keys
             at ./tfhe/src/high_level_api/keys/mod.rs:35:21
  22: pbs_count::main
             at ./tfhe/examples/pbs_count.rs:7:22
  23: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by IceTDrinker** [comment]
Use the features

--features=x86_64-unix

**Comment by IceTDrinker** [comment]
See https://docs.zama.ai/tfhe-rs/getting-started/installation to configure with the right features @qxzhou1010

**Comment by IceTDrinker** [comment]
@qxzhou1010 did this solve your issue ?

**Comment by IceTDrinker** [comment]
as indicated @qxzhou1010 you need to enable features to get an entropy source like the error message says, if you still have issues feel free to opne new ones.

Cheers
